[workspace]
resolver = "2"

[package]
name = "bin_throw"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.1" }
bevy_rapier3d = { version = "*", features = [ "simd-nightly" ] }
